//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did participant use the SBI framework to effectively navigate the discussion? Yes
        ///Did participant proactively identify and seize opportunities to advance goals without explicit direction? No - While Trish effectively
        ///Did participant demonstrate effective interview skills? Yes - Kathryn asked relevant questions, maintained a professional demeanor, and sought to understand the candidate&apos;s experience and problem-solving abilities.
        ///Did participant use the SBI framework to effectively navigate the discussion? [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdditionQuestionsInReport {
            get {
                return ResourceManager.GetString("AdditionQuestionsInReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to practissnosql.
        /// </summary>
        public static string CosmosDatataseName {
            get {
                return ResourceManager.GetString("CosmosDatataseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountEndpoint=https://practisscosmosdbaccount.documents.azure.com:443/;AccountKey=d9kYFfDuFy5N4CuzOy6mI3vs2ZXfbYMFWjyiWVNXpunczz4U0ypElggxMbZEkejAAsAHoQ0IKc2oACDb3bwGJQ==;.
        /// </summary>
        public static string CosmosDbConnectionString {
            get {
                return ResourceManager.GetString("CosmosDbConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Additional Questions**:
        ///
        ///*   Did Joe demonstrate effective adaptation when faced with new information or challenges? [Yes] [Absolutely thrilled with how joe did.] 
        ///*   Did Joe proactively identify and seize opportunities to advance goals without explicit direction?  [Yes] Joe did really well..
        /// </summary>
        public static string ReportEvaluation {
            get {
                return ResourceManager.GetString("ReportEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///&lt;title&gt;Email Content&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div style=&quot;font-family: Arial, sans-serif; color: #333;&quot;&gt;
        ///  &lt;h2 style=&quot;color: #0056b3;&quot;&gt;Hello!&lt;/h2&gt;
        ///  &lt;p&gt;We are excited to share the latest updates with you.&lt;/p&gt;
        ///  &lt;p&gt;Check out our new features that can help you increase your productivity!&lt;/p&gt;
        ///  &lt;a href=&quot;https://www.yourwebsite.com&quot; target=&quot;_blank&quot; style=&quot;background-col [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestEmailHtmlBody {
            get {
                return ResourceManager.GetString("TestEmailHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Title:** Navigating Conflict Management in the Workplace
        ///
        ///**Description:**
        ///- Understand the dynamics of conflict in professional settings.
        ///- Learn strategies for effective conflict resolution.
        ///- Practice communication techniques that de-escalate tension.
        ///
        ///**Scenario for AI Interaction:** 
        ///Your name is Michael. You are playing the role of a team leader in a corporate setting. A conflict has arisen between two team members over the allocation of resources for a project, leading to tension within the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TestModuleParseInput {
            get {
                return ResourceManager.GetString("TestModuleParseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alex@grw.ai	Alex McNaughten
        ///bianca.hayes@tmsconsulting.com.au	Bianca Hayes
        ///trish.cloete@tmsconsulting.com.au	Trish Cloete
        ///mark.kane@tmsconsulting.com.au	Mark Kane
        ///jeff@salesassembly.com	Jeff Rosset
        ///jeff@projectoty.com	Jeff Otis
        ///colin.campbell@joinpavilion.com	Colin Campbell
        ///josh.carter@joinpavilion.com	Josh Carter
        ///sam@joinpavilion.com	Sam Jacobs
        ///kathleen@joinpavilion.com	Kathleen Booth
        ///kalkat@humantic.ai	Amarpreet Kalkat
        ///neeraj@humanticai.com	Neeraj Singh
        ///diannawinegarden@gmail.com	Dianna Winega [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Whitelisters {
            get {
                return ResourceManager.GetString("Whitelisters", resourceCulture);
            }
        }
    }
}
