//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractissWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PractissWeb.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief description of what the module aims to teach or the skills it intends to develop
        ///
        ///Example:
        ///This role play scenario is designed to simulate a realistic workplace interaction where a supervisor addresses an employee&apos;s repeated failure to meet project deadlines. The module emphasizes the art of delivering and responding to constructive feedback, encouraging a productive dialogue that seeks to identify underlying issues, improve performance, and foster professional growth. Participants will engage in a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ModuleDescription_Default {
            get {
                return ResourceManager.GetString("ModuleDescription_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModuleEvaluation_Default {
            get {
                return ResourceManager.GetString("ModuleEvaluation_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief description of the scenario being role-played, outlining the context and the specific issue or task that needs to be addressed
        ///
        ///Example:
        ///Imagine a scenario where I am the supervisor, and you are my employee who has missed the project deadline three times. This setup is an opportunity for me to practice giving constructive feedback.
        ///
        ///In our interaction, you will sensitively react to my criticism, either by justifying your actions or subtly deflecting the feedback. Your responses will be brief and  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ModuleSituation_Default {
            get {
                return ResourceManager.GetString("ModuleSituation_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expert instruction designer has created instructions used by AI to roleplay a situation with a human learner. Here are 24 such situations created by them. I will then give you raw data from an inexperienced instruction designer and you will need to convert it into the format which the expert has created. 
        ///
        ///
        ///--------------------------------------------
        ///
        ///**Title:** Addressing Team Complaints: A Leadership Development Scenario (Challenging)
        ///
        ///
        ///**Description:** The corporate manager has scheduled a me [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PromptModuleCreateWizard {
            get {
                return ResourceManager.GetString("PromptModuleCreateWizard", resourceCulture);
            }
        }
    }
}
