//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleWorker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleWorker.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to practissnosql.
        /// </summary>
        internal static string CosmosDatataseName {
            get {
                return ResourceManager.GetString("CosmosDatataseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountEndpoint=https://practisscosmosdbaccount.documents.azure.com:443/;AccountKey=d9kYFfDuFy5N4CuzOy6mI3vs2ZXfbYMFWjyiWVNXpunczz4U0ypElggxMbZEkejAAsAHoQ0IKc2oACDb3bwGJQ==;.
        /// </summary>
        internal static string CosmosDbConnectionString {
            get {
                return ResourceManager.GetString("CosmosDbConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///    &quot;name&quot;: &quot;GetRoleplaysToImproveProfessionalSkills&quot;,
        ///    &quot;description&quot;: &quot;Provides structured advice / insight and role-playing scenarios to help individuals enhance specific professional skills.&quot;,
        ///    &quot;parameters&quot;: {
        ///        &quot;type&quot;: &quot;object&quot;,
        ///        &quot;properties&quot;: {
        ///            &quot;communicationSkillsFeedback&quot;: {
        ///                &quot;type&quot;: &quot;object&quot;,
        ///                &quot;properties&quot;: {
        ///                    &quot;participantName&quot;: {
        ///                        &quot;type&quot;: &quot;string&quot;,
        ///                        &quot;descriptio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Function_GetRoleplaysToImproveProfessionalSkills {
            get {
                return ResourceManager.GetString("Function_GetRoleplaysToImproveProfessionalSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think carefully and logically. Analyze the meeting transcript, focusing specifically on the contributions of participant {0}, whose bio is:
        ///
        ///{1}.
        ///
        ///Review the meeting transcript focusing on one participant - {0}, identifying the roles, motivations, aspirations for the participants and the best possible outcome. As a seasoned communicator, inspire action, or influence outcomes, and expert at steering meetings towards its objectives, identify their areas for improvement in assertiveness, clarity, and confl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImproveProfessionalSkillsSystemPrompt {
            get {
                return ResourceManager.GetString("ImproveProfessionalSkillsSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the meeting transcript focusing on one participant - {0}, identifying the roles, motivations, aspirations for the participants and the best possible outcome. As a seasoned communicator, inspire action, or influence outcomes, and expert at steering meetings towards its objectives, identify their areas for improvement in assertiveness, clarity, and conflict resolution. When suggesting {0} could do something better, provide specific examples from the transcript, suggest detailed effective response phras [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecommendRoleplaysFromReportSystemPrompt {
            get {
                return ResourceManager.GetString("RecommendRoleplaysFromReportSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think carefully and logically. Analyze the meeting transcript, focusing specifically on the contributions of participant {0}, whose bio is:
        ///
        ///{1}.
        ///
        ///Review the meeting transcript focusing on one participant - {0}, identifying the roles, motivations, aspirations for the participants and the best possible outcome. As a seasoned communicator, inspire action, or influence outcomes, and expert at steering meetings towards its objectives, identify their areas for improvement in assertiveness, clarity, and confl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecommendRoleplaysFromTranscriptSystemPrompt {
            get {
                return ResourceManager.GetString("RecommendRoleplaysFromTranscriptSystemPrompt", resourceCulture);
            }
        }
    }
}
