//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiIntegrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApiIntegrations.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;service_account&quot;,
        ///  &quot;project_id&quot;: &quot;practissmvp&quot;,
        ///  &quot;private_key_id&quot;: &quot;1409a5d17d3cd357a8d4791b91f165db5e0e2726&quot;,
        ///  &quot;private_key&quot;: &quot;-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2oe1o111KwwTu\nop6RokEb7UIDMCfcg2CCOwGjuT/aeNNJaEYwxU8Mo5OM2I6dDEmEtqOc21BooM22\nSm2wzB1tf6CcwU5Xww2IbkkuyfopvDe4ars0hVvHe/GYeFf5L0e2OAgeCRC7Wlz0\no3JWN5m39lDb+IQB4CXRh60N55UGhvbN5b0lF/8uQZqevy8ZbByL2sE0AzJLvJ++\nGHEGGW2rFs+wedeaeWh4Smf9A01hn5+inTVvZuIBvQPh0FturjcwYpn6rZh2jD9P\nbRsEz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GoogleSpreadsheetAccessApiKeyJson {
            get {
                return ResourceManager.GetString("GoogleSpreadsheetAccessApiKeyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1LXFMCE-CG7bk3K5bljA_itg0k-kEibxwSrll3o_3IH4.
        /// </summary>
        public static string TemplateSpreadsheetId {
            get {
                return ResourceManager.GetString("TemplateSpreadsheetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Q6Ir63NSwN9rLD0Mn5VCQeidx71hVzn1PPul_1JkpX8.
        /// </summary>
        public static string WhitelistSpreadsheetId {
            get {
                return ResourceManager.GetString("WhitelistSpreadsheetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        ///  .email-container {{(
        ///    width: 100%;
        ///    max-width: 600px;
        ///    margin: auto;
        ///    text-align: center;
        ///    font-family: Arial, sans-serif;
        ///  }}
        ///  .action-detail {{
        ///    font-size: 24px;
        ///    font-weight: bold;
        ///    color: #000;
        ///    padding: 15px;
        ///    background-color: #f0f0f0;
        ///    display: inline-block;
        ///    margin: 20px auto;
        ///  }}
        ///  .instruction-text {{
        ///    font-size: 16px;
        ///    color: #333;
        ///  }}
        ///  .highlight {{
        ///    color: #007BFF;
        ///    font-weight [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WhitelistUserActionNotification {
            get {
                return ResourceManager.GetString("WhitelistUserActionNotification", resourceCulture);
            }
        }
    }
}
