//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PractissWorkflow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PractissWorkflow.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        ///
        ///**Additional Questions**: [Think really carefully and logically and answer this question. Answer Yes only if you are extremely confident.].
        /// </summary>
        public static string AdditionalQuestionsPrefix {
            get {
                return ResourceManager.GetString("AdditionalQuestionsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think carefully and logically, explaining your answer. You are a top evaluator in the learner&apos;s field with a keen interest in helping them hone their abilities, your task is to carefully review their roleplay performance and provide a detailed report. It is Imperative to use illustrative examples with specific quotes based on specific instances from the role play. Provide specific examples and alternate responses in the areas of improvement section.
        ///
        ///It is not just about finding areas of weakness - also h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentPrompt {
            get {
                return ResourceManager.GetString("ContentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think carefully and logically, explaining your answer. You are a top evaluator in the learner&apos;s field with a keen interest in helping them hone their abilities, your task is to carefully review their roleplay performance and provide a detailed report. It is Imperative to use illustrative examples with specific quotes based on specific instances from the role play. Provide specific examples and alternate responses in the areas of improvement section.
        ///
        ///It is not just about finding areas of weakness - also h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentPromptV2 {
            get {
                return ResourceManager.GetString("ContentPromptV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Think carefully and logically, explaining your answer. You are a top evaluator in the learner&apos;s field with a keen interest in helping them hone their abilities, your task is to carefully review their roleplay performance and provide a detailed report. It is Imperative to use illustrative examples with specific quotes based on specific instances from the role play. Provide specific examples and alternate responses in the areas of improvement section.
        ///
        ///It is not just about finding areas of weakness - also h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentPromptV3 {
            get {
                return ResourceManager.GetString("ContentPromptV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;As a top evaluator in the learner&apos;s field with a keen interest in helping him hone their abilities, your task is to carefully review their roleplay performance and provide a detailed report. The report should follow a hierarchical structure, use markdown format. It is  Imperative to use use illustrative examples with specific quotes based on specific instances from the role play. each quotes should be listed as much as possible in its own sub section. provide specific examples and alternate responses in th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Default_Eval_Prompt_Suffix {
            get {
                return ResourceManager.GetString("Default_Eval_Prompt_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;generate_roleplay_response&quot;,
        ///    &quot;description&quot;: &quot;Generates a response for a roleplay scenario based on the given context and participant&apos;s input, including an emotional state and status indicator associated with the response.&quot;,
        ///    &quot;parameters&quot;: {
        ///      &quot;type&quot;: &quot;object&quot;,
        ///      &quot;properties&quot;: {
        ///        &quot;dialog_response&quot;: {
        ///          &quot;type&quot;: &quot;string&quot;,
        ///          &quot;description&quot;: &quot;The generated dialogue response from ChatGPT based on the roleplay scenario and participant&apos;s input.&quot;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Function_Generate_Roleplay_Response {
            get {
                return ResourceManager.GetString("Function_Generate_Roleplay_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        /// You (the model) are {0}. The other most important person described in the scenario is me ({1}). You are speaking with me {1}. Lets roleplay. Focus solely on {0}&apos;s lines of dialogue, and just one at a time. Please provide only {0}&apos;s spoken dialogue. Let&apos;s go Start the conversation with {0}&apos;s(your) first line, usually greeting me as you walk into my office. Do not include any descriptions or formatting. Please provide only {0}&apos;s spoken dialogue..
        /// </summary>
        public static string Prompt_Situation_Suffix {
            get {
                return ResourceManager.GetString("Prompt_Situation_Suffix", resourceCulture);
            }
        }
    }
}
