//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAADM5JREFUeJzt3Xmwl1Udx/H3hQvKloIgIggCJosLbomCicSYqaVjqWOlpo7ZMDb91zpT06KZjY2VNdm0uY01Tn+EmoRLjhZlLi2EiMmipiyyynblytIf33uDQcB7f79zzvd5zvm8Zr5zGcd5nu/v/M7392znOQdERERERERERERERERERERklxbvBArSA5gATAImAmOAkcChwCFAX6B3x//bDmwG1gJvAK8AS4AFwL+AhcCOhLkXSwUS1/HAucAM4DRgQKDtvgk8BTwGzAbmB9quSHQTge8Ai4GdieIl4EZgXILPJ9JtrcBlwFzSFcW+4kngUqBn1E8s0gW9gZnAy/gXxp6xBLgOK16R5C4DluJfCO8Wi4GLI7WByDtMwE5jvDt+d+OPwNER2kMEsHP6rwBv4d/ZG402 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlankProfileBase64 {
            get {
                return ResourceManager.GetString("BlankProfileBase64", resourceCulture);
            }
        }
    }
}
